spring:
  jpa:
    show-sql: true
#    hibernate:
#      database-platform: org.hibernate.dialect.H2Dialect
#      ddl-auto: always
  datasource:
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:file:./testDb2;MODE=MySQL
    driverClassName: org.hsqldb.jdbcDriver
    url: jdbc:hsqldb:mem://localhost/blogdb;shutdown=true
    username: hsp
    initialization-mode: ALWAYS
    password:
    ##数据初始化设置
    #进行该配置后，每次启动程序，程序都会运行resources/db/schema.sql文件，对数据库的结构进行操作。
#    schema: classpath:schema/init.sql
    #进行该配置后，每次启动程序，程序都会运行resources/db/data.sql文件，对数据库的数据操作。
#    data: classpath:db/data.sql
    ##h2 web console设置
    #表明使用的数据库平台是h2
    platform: h2
  # 进行该配置后，h2 web consloe就可以在远程访问了。否则只能在本机访问。
  h2:
    console:
      settings:
        web-allow-others: true
      #进行该配置，你就可以通过YOUR_URL/h2访问h2 web consloe。YOUR_URL是你程序的访问URl。
      path: /h2
      #进行该配置，程序开启时就会启动h2 web consloe。当然这是默认的，如果你不想在启动程序时启动h2 web consloe，那么就设置为false。
      enabled: true